namespace CsArchViewer.Avalonia.ViewModels;

public sealed class LocalizationService
{
    private readonly Dictionary<string, Dictionary<string, string>> _resources = new(StringComparer.OrdinalIgnoreCase)
    {
        ["zh-TW"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["WorkspaceTab"] = "工作區",
            ["SettingsTab"] = "設定",
            ["OpenFolder"] = "開啟資料夾",
            ["Reload"] = "重新載入",
            ["Export"] = "匯出",
            ["SearchPlaceholder"] = "搜尋專案...",
            ["Nodes"] = "節點",
            ["NodeDetails"] = "節點詳情",
            ["ProjectName"] = "專案名稱",
            ["NodeType"] = "節點類型",
            ["FullPath"] = "完整路徑",
            ["TargetFramework"] = "目標框架",
            ["OutputType"] = "輸出類型",
            ["ProjectReferences"] = "專案參考",
            ["PackageReferences"] = "套件參考",
            ["Extension"] = "副檔名",
            ["SizeBytes"] = "大小（位元組）",
            ["LastModified"] = "最後修改時間",
            ["ChildCount"] = "子項目數量",
            ["ReferencedNamespaces"] = "被參考命名空間",
            ["ReferencedBy"] = "被參考者",
            ["Rule"] = "規則",
            ["Source"] = "來源",
            ["Target"] = "目標",
            ["Message"] = "訊息",
            ["FullTypeName"] = "完整型別名稱",
            ["Namespace"] = "命名空間",
            ["File"] = "檔案",
            ["BaseType"] = "基底型別",
            ["ImplementedInterfaces"] = "實作介面",
            ["ReferencedTypes"] = "被參考型別",
            ["DependencyMatrixRow"] = "相依矩陣列",
            ["DependsOn"] = "相依目標",
            ["IncomingDependencies"] = "流入相依",
            ["DependencyCount"] = "相依數量",
            ["CircularDependencyCount"] = "循環相依數量",
            ["ViolationCount"] = "違規數量",
            ["LineCount"] = "行數",
            ["Diagnostics"] = "診斷",
            ["OverlayMode"] = "覆蓋模式",
            ["MetricsFilter"] = "度量篩選",
            ["MetricsTab"] = "度量儀表板",
            ["TopCoupledNamespaces"] = "高耦合命名空間",
            ["HealthWarnings"] = "健康警告",
            ["TopFilesByLineCount"] = "檔案行數排行",
            ["LinesUnit"] = "行",
            ["TotalLoc"] = "總 LOC",
            ["TotalFiles"] = "總檔案數",
            ["LargestFile"] = "最大檔案",
            ["LargestNamespace"] = "最大命名空間",
            ["CircularDependencies"] = "循環相依",
            ["LayerViolations"] = "分層違規",
            ["SettingsTitle"] = "設定",
            ["SettingsDescription"] = "外觀與圖表顯示選項。",
            ["GraphSection"] = "圖表",
            ["ShowLineCount"] = "在節點上顯示行數",
            ["Language"] = "語言",
            ["StatusIdle"] = "請選擇要分析的資料夾。",
            ["StatusIdleShort"] = "閒置",
            ["StatusTasks"] = "工作",
            ["StatusGraphTemplate"] = "圖表: {0} | 節點: {1} | 邊: {2}",
            ["SelectFolderTitle"] = "選擇 .NET 方案資料夾",
            ["ExportTitleTemplate"] = "匯出 {0}",
            ["ExportedTemplate"] = "已匯出 {0}: {1}",
            ["ExportUnavailableGraph"] = "目前沒有可匯出的圖表資料。請先選擇資料夾並完成分析。",
            ["ExportUnavailableMetrics"] = "目前沒有可匯出的度量資料。請先完成分析。",
            ["ExportFailedTemplate"] = "匯出失敗: {0}",
            ["ExportCanceled"] = "已取消匯出。",
            ["OpenedFileTemplate"] = "已開啟檔案: {0}",
            ["OpenFileNotFoundTemplate"] = "找不到檔案: {0}",
            ["OpenFileFailedTemplate"] = "開啟檔案失敗: {0}",
            ["RunningFullAnalysis"] = "正在執行完整分析...",
            ["FileChangedTemplate"] = "檔案變更: {0}",
            ["FullAnalysisCompleted"] = "完整分析完成。",
            ["IncrementalUpdatedTemplate"] = "增量分析已更新: {0}",
            ["AnalysisFailedTemplate"] = "分析失敗: {0}",
            ["AnalyzeFailedTemplate"] = "分析失敗: {0}",
            ["FolderNoChildTemplate"] = "資料夾 '{0}' 沒有可顯示的子項。",
            ["SymbolExplorerTab"] = "符號瀏覽",
            ["SymbolExplorerSearchPlaceholder"] = "搜尋型別、方法、命名空間…",
            ["SymbolExplorerSearch"] = "搜尋",
            ["SymbolExplorerDetailsTab"] = "符號詳情",
            ["SymbolExplorerFindRefs"] = "尋找參考",
            ["SymbolExplorerGoToDef"] = "移至定義",
            ["SymbolExplorerTypeMembersTitle"] = "型別成員（輕量分析）",
            ["SymbolExplorerMethodMetaTitle"] = "方法詮釋資料",
            ["BottomPanelDiagnosticsTab"] = "診斷 / 檔案排行",
            ["SymbolExplorerReferencesTab"] = "符號參考結果",
            ["SymbolExplorerJumpOpen"] = "開啟選取位置",
            ["SymbolExplorerNoIndex"] = "符號索引尚未就緒；請先完成分析。",
            ["SymbolExplorerNoSelection"] = "請先選取符號。",
            ["GroupBy"] = "分組方式",
            ["FitToScreen"] = "適應畫面",
            ["ZoomToSelection"] = "縮放至選取",
            ["CompactRelated"] = "拉近關聯",
            ["RestoreGraphPositions"] = "回復圖位置",
            ["ResetViewDefaults"] = "預設",
            ["FocusNeighborhoodOnly"] = "僅顯示選取節點關聯",
            ["ToolbarMore"] = "更多選項",
            ["ToolbarLess"] = "收合選項",
            ["DependencyPathTab"] = "相依路徑",
            ["DependencyPathSource"] = "起點",
            ["DependencyPathTarget"] = "目標",
            ["DependencyPathShortest"] = "最短路徑",
            ["DependencyPathCycle"] = "尋找循環",
            ["DiagnosticsSeverityFilter"] = "診斷層級",
            ["ExportDiagnostics"] = "匯出診斷",
            ["RecentSearches"] = "最近搜尋",
            ["LogsTab"] = "記錄",
            ["Performance"] = "效能",
            ["RestoreLastSession"] = "啟動時還原上次工作區",
            ["AutoSaveSession"] = "自動儲存工作區",
            ["Theme"] = "主題",
            ["GraphLayout"] = "圖表版面"
        },
        ["en-US"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["WorkspaceTab"] = "Workspace",
            ["SettingsTab"] = "Settings",
            ["OpenFolder"] = "Open Folder",
            ["Reload"] = "Reload",
            ["Export"] = "Export",
            ["SearchPlaceholder"] = "Search project...",
            ["Nodes"] = "Nodes",
            ["NodeDetails"] = "Node Details",
            ["ProjectName"] = "Project Name",
            ["NodeType"] = "Node Type",
            ["FullPath"] = "Full Path",
            ["TargetFramework"] = "Target Framework",
            ["OutputType"] = "Output Type",
            ["ProjectReferences"] = "Project References",
            ["PackageReferences"] = "Package References",
            ["Extension"] = "Extension",
            ["SizeBytes"] = "Size (bytes)",
            ["LastModified"] = "Last Modified",
            ["ChildCount"] = "Child Count",
            ["ReferencedNamespaces"] = "Referenced Namespaces",
            ["ReferencedBy"] = "Referenced By",
            ["Rule"] = "Rule",
            ["Source"] = "Source",
            ["Target"] = "Target",
            ["Message"] = "Message",
            ["FullTypeName"] = "Full Type Name",
            ["Namespace"] = "Namespace",
            ["File"] = "File",
            ["BaseType"] = "Base Type",
            ["ImplementedInterfaces"] = "Implemented Interfaces",
            ["ReferencedTypes"] = "Referenced Types",
            ["DependencyMatrixRow"] = "Dependency Matrix Row",
            ["DependsOn"] = "Depends On",
            ["IncomingDependencies"] = "Incoming Dependencies",
            ["DependencyCount"] = "Dependency Count",
            ["CircularDependencyCount"] = "Circular Dependency Count",
            ["ViolationCount"] = "Violation Count",
            ["LineCount"] = "Line Count",
            ["Diagnostics"] = "Diagnostics",
            ["OverlayMode"] = "Overlay Mode",
            ["MetricsFilter"] = "Metrics Filter",
            ["MetricsTab"] = "Metrics Dashboard",
            ["TopCoupledNamespaces"] = "Most Coupled Namespaces",
            ["HealthWarnings"] = "Health Warnings",
            ["TopFilesByLineCount"] = "Top Files by LOC",
            ["LinesUnit"] = "lines",
            ["TotalLoc"] = "Total LOC",
            ["TotalFiles"] = "Total Files",
            ["LargestFile"] = "Largest File",
            ["LargestNamespace"] = "Largest Namespace",
            ["CircularDependencies"] = "Circular Dependencies",
            ["LayerViolations"] = "Layer Violations",
            ["SettingsTitle"] = "Settings",
            ["SettingsDescription"] = "Appearance and graph display options.",
            ["GraphSection"] = "Graph",
            ["ShowLineCount"] = "Show line count on nodes",
            ["Language"] = "Language",
            ["StatusIdle"] = "Select a folder to analyze.",
            ["StatusIdleShort"] = "Idle",
            ["StatusTasks"] = "Tasks",
            ["StatusGraphTemplate"] = "Graph: {0} | Nodes: {1} | Edges: {2}",
            ["SelectFolderTitle"] = "Select .NET solution folder",
            ["ExportTitleTemplate"] = "Export {0}",
            ["ExportedTemplate"] = "Exported {0}: {1}",
            ["ExportUnavailableGraph"] = "No graph is available to export. Please select a folder and finish analysis first.",
            ["ExportUnavailableMetrics"] = "No metrics are available to export yet. Please finish analysis first.",
            ["ExportFailedTemplate"] = "Export failed: {0}",
            ["ExportCanceled"] = "Export canceled.",
            ["OpenedFileTemplate"] = "Opened file: {0}",
            ["OpenFileNotFoundTemplate"] = "File not found: {0}",
            ["OpenFileFailedTemplate"] = "Failed to open file: {0}",
            ["RunningFullAnalysis"] = "Running full analysis...",
            ["FileChangedTemplate"] = "File changed: {0}",
            ["FullAnalysisCompleted"] = "Full analysis completed.",
            ["IncrementalUpdatedTemplate"] = "Incremental analysis updated: {0}",
            ["AnalysisFailedTemplate"] = "Analysis failed: {0}",
            ["AnalyzeFailedTemplate"] = "Analyze failed: {0}",
            ["FolderNoChildTemplate"] = "Folder '{0}' has no child items to display.",
            ["SymbolExplorerTab"] = "Symbol Explorer",
            ["SymbolExplorerSearchPlaceholder"] = "Search types, methods, namespaces…",
            ["SymbolExplorerSearch"] = "Search",
            ["SymbolExplorerDetailsTab"] = "Symbol Details",
            ["SymbolExplorerFindRefs"] = "Find References",
            ["SymbolExplorerGoToDef"] = "Go To Definition",
            ["SymbolExplorerTypeMembersTitle"] = "Type members (lightweight)",
            ["SymbolExplorerMethodMetaTitle"] = "Method metadata",
            ["BottomPanelDiagnosticsTab"] = "Diagnostics / Top Files",
            ["SymbolExplorerReferencesTab"] = "Symbol References",
            ["SymbolExplorerJumpOpen"] = "Open Selected",
            ["SymbolExplorerNoIndex"] = "Symbol index not ready; finish analysis first.",
            ["SymbolExplorerNoSelection"] = "Select a symbol first.",
            ["GroupBy"] = "Group By",
            ["FitToScreen"] = "Fit To Screen",
            ["ZoomToSelection"] = "Zoom To Selection",
            ["CompactRelated"] = "Compact Related",
            ["RestoreGraphPositions"] = "Restore Graph Positions",
            ["ResetViewDefaults"] = "Reset Defaults",
            ["FocusNeighborhoodOnly"] = "Show selected node neighborhood only",
            ["ToolbarMore"] = "More Options",
            ["ToolbarLess"] = "Collapse Options",
            ["DependencyPathTab"] = "Dependency Path",
            ["DependencyPathSource"] = "Source",
            ["DependencyPathTarget"] = "Target",
            ["DependencyPathShortest"] = "Shortest Path",
            ["DependencyPathCycle"] = "Find Cycle",
            ["DiagnosticsSeverityFilter"] = "Diagnostics Severity",
            ["ExportDiagnostics"] = "Export Diagnostics",
            ["RecentSearches"] = "Recent Searches",
            ["LogsTab"] = "Logs",
            ["Performance"] = "Performance",
            ["RestoreLastSession"] = "Restore last workspace on startup",
            ["AutoSaveSession"] = "Auto-save workspace",
            ["Theme"] = "Theme",
            ["GraphLayout"] = "Graph Layout"
        }
    };

    private string _languageCode = "zh-TW";

    public event Action? LanguageChanged;

    public string LanguageCode => _languageCode;

    public string Get(string key)
    {
        if (_resources.TryGetValue(_languageCode, out var langMap) &&
            langMap.TryGetValue(key, out var value))
        {
            return value;
        }

        return _resources["en-US"].TryGetValue(key, out var fallback) ? fallback : key;
    }

    public void SetLanguage(string languageCode)
    {
        if (_resources.ContainsKey(languageCode) && !string.Equals(_languageCode, languageCode, StringComparison.OrdinalIgnoreCase))
        {
            _languageCode = languageCode;
            LanguageChanged?.Invoke();
        }
    }
}
