namespace CsArchViewer.Avalonia.ViewModels;

public sealed partial class MainWindowViewModel
{
    public string WorkspaceTabText => L("WorkspaceTab");
    public string SettingsTabText => L("SettingsTab");
    public string UpdatesTabText => L("UpdatesTab");
    public string OpenFolderText => L("OpenFolder");
    public string ReloadText => L("Reload");
    public string ExportText => L("Export");
    public string SearchPlaceholderText => L("SearchPlaceholder");
    public string NodesTitleText => L("Nodes");
    public string NodeDetailsTitleText => L("NodeDetails");
    public string ProjectNameText => L("ProjectName");
    public string NodeTypeText => L("NodeType");
    public string FullPathText => L("FullPath");
    public string TargetFrameworkText => L("TargetFramework");
    public string OutputTypeText => L("OutputType");
    public string ProjectReferencesText => L("ProjectReferences");
    public string PackageReferencesText => L("PackageReferences");
    public string ExtensionText => L("Extension");
    public string SizeBytesText => L("SizeBytes");
    public string LastModifiedText => L("LastModified");
    public string ChildCountText => L("ChildCount");
    public string ReferencedNamespacesText => L("ReferencedNamespaces");
    public string ReferencedByText => L("ReferencedBy");
    public string RuleText => L("Rule");
    public string SourceText => L("Source");
    public string TargetText => L("Target");
    public string MessageText => L("Message");
    public string FullTypeNameText => L("FullTypeName");
    public string NamespaceText => L("Namespace");
    public string FileText => L("File");
    public string BaseTypeText => L("BaseType");
    public string ImplementedInterfacesText => L("ImplementedInterfaces");
    public string ReferencedTypesText => L("ReferencedTypes");
    public string DependencyMatrixRowText => L("DependencyMatrixRow");
    public string DependsOnText => L("DependsOn");
    public string IncomingDependenciesText => L("IncomingDependencies");
    public string DependencyCountText => L("DependencyCount");
    public string CircularDependencyCountText => L("CircularDependencyCount");
    public string ViolationCountText => L("ViolationCount");
    public string LineCountText => L("LineCount");
    public string DiagnosticsTitleText => L("Diagnostics");
    public string OverlayModeText => L("OverlayMode");
    public string MetricsFilterText => L("MetricsFilter");
    public string MetricsTabText => L("MetricsTab");
    public string TopCoupledNamespacesText => L("TopCoupledNamespaces");
    public string HealthWarningsText => L("HealthWarnings");
    public string TopFilesByLineCountText => L("TopFilesByLineCount");
    public string LinesUnitText => L("LinesUnit");
    public string SettingsTitleText => L("SettingsTitle");
    public string SettingsDescriptionText => L("SettingsDescription");
    public string GraphSectionText => L("GraphSection");
    public string ShowLineCountText => L("ShowLineCount");
    public string LanguageText => L("Language");
    public string TotalLocText => L("TotalLoc");
    public string TotalFilesText => L("TotalFiles");
    public string LargestFileText => L("LargestFile");
    public string LargestNamespaceText => L("LargestNamespace");
    public string CircularDependenciesText => L("CircularDependencies");
    public string LayerViolationsText => L("LayerViolations");
    public string SymbolExplorerTabText => L("SymbolExplorerTab");
    public string SymbolExplorerSearchPlaceholderText => L("SymbolExplorerSearchPlaceholder");
    public string SymbolExplorerSearchButtonText => L("SymbolExplorerSearch");
    public string SymbolExplorerDetailsTabText => L("SymbolExplorerDetailsTab");
    public string SymbolExplorerFindRefsText => L("SymbolExplorerFindRefs");
    public string SymbolExplorerGoToDefText => L("SymbolExplorerGoToDef");
    public string SymbolExplorerTypeMembersTitleText => L("SymbolExplorerTypeMembersTitle");
    public string SymbolExplorerMethodMetaTitleText => L("SymbolExplorerMethodMetaTitle");
    public string BottomPanelDiagnosticsTabText => L("BottomPanelDiagnosticsTab");
    public string SymbolExplorerReferencesTabText => L("SymbolExplorerReferencesTab");
    public string SymbolExplorerJumpOpenText => L("SymbolExplorerJumpOpen");
    public string GroupByText => L("GroupBy");
    public string FitToScreenText => L("FitToScreen");
    public string ZoomToSelectionText => L("ZoomToSelection");
    public string CompactRelatedText => L("CompactRelated");
    public string RestoreGraphPositionsText => L("RestoreGraphPositions");
    public string ResetViewDefaultsText => L("ResetViewDefaults");
    public string FocusNeighborhoodOnlyText => L("FocusNeighborhoodOnly");
    public string DependencyPathTabText => L("DependencyPathTab");
    public string DependencyPathSourceTextLabel => L("DependencyPathSource");
    public string DependencyPathTargetTextLabel => L("DependencyPathTarget");
    public string DependencyPathShortestText => L("DependencyPathShortest");
    public string DependencyPathCycleText => L("DependencyPathCycle");
    public string DiagnosticsSeverityFilterText => L("DiagnosticsSeverityFilter");
    public string ExportDiagnosticsText => L("ExportDiagnostics");
    public string RecentSearchesText => L("RecentSearches");
    public string LogsTabText => L("LogsTab");
    public string PerformanceText => L("Performance");
    public string RestoreLastSessionText => L("RestoreLastSession");
    public string AutoSaveSessionText => L("AutoSaveSession");
    public string ThemeText => L("Theme");
    public string GraphLayoutText => L("GraphLayout");
    public string CurrentVersionText => L("CurrentVersion");
    public string AvailableVersionsText => L("AvailableVersions");
    public string RefreshVersionsText => L("RefreshVersions");
    public string SwitchVersionText => L("SwitchVersion");
    public string UpdateHintText => L("UpdateHint");

    public int MetricsTotalLoc => _metricsSummary?.TotalLoc ?? 0;
    public int MetricsTotalFiles => _metricsSummary?.TotalFiles ?? 0;
    public string MetricsLargestFile => _metricsSummary?.LargestFile?.FileName ?? "-";
    public string MetricsLargestNamespace => _metricsSummary?.LargestNamespace?.Namespace ?? "-";
    public int MetricsCircularDependencies => _metricsSummary?.CircularDependencyCount ?? 0;
    public int MetricsLayerViolations => _metricsSummary?.LayerViolationCount ?? 0;

    public string L(string key) => _localization.Get(key);

    private void HandleLanguageChanged()
    {
        OnPropertyChanged(nameof(WorkspaceTabText));
        OnPropertyChanged(nameof(SettingsTabText));
        OnPropertyChanged(nameof(UpdatesTabText));
        OnPropertyChanged(nameof(OpenFolderText));
        OnPropertyChanged(nameof(ReloadText));
        OnPropertyChanged(nameof(ExportText));
        OnPropertyChanged(nameof(SearchPlaceholderText));
        OnPropertyChanged(nameof(NodesTitleText));
        OnPropertyChanged(nameof(NodeDetailsTitleText));
        OnPropertyChanged(nameof(ProjectNameText));
        OnPropertyChanged(nameof(NodeTypeText));
        OnPropertyChanged(nameof(FullPathText));
        OnPropertyChanged(nameof(TargetFrameworkText));
        OnPropertyChanged(nameof(OutputTypeText));
        OnPropertyChanged(nameof(ProjectReferencesText));
        OnPropertyChanged(nameof(PackageReferencesText));
        OnPropertyChanged(nameof(ExtensionText));
        OnPropertyChanged(nameof(SizeBytesText));
        OnPropertyChanged(nameof(LastModifiedText));
        OnPropertyChanged(nameof(ChildCountText));
        OnPropertyChanged(nameof(ReferencedNamespacesText));
        OnPropertyChanged(nameof(ReferencedByText));
        OnPropertyChanged(nameof(RuleText));
        OnPropertyChanged(nameof(SourceText));
        OnPropertyChanged(nameof(TargetText));
        OnPropertyChanged(nameof(MessageText));
        OnPropertyChanged(nameof(FullTypeNameText));
        OnPropertyChanged(nameof(NamespaceText));
        OnPropertyChanged(nameof(FileText));
        OnPropertyChanged(nameof(BaseTypeText));
        OnPropertyChanged(nameof(ImplementedInterfacesText));
        OnPropertyChanged(nameof(ReferencedTypesText));
        OnPropertyChanged(nameof(DependencyMatrixRowText));
        OnPropertyChanged(nameof(DependsOnText));
        OnPropertyChanged(nameof(IncomingDependenciesText));
        OnPropertyChanged(nameof(DependencyCountText));
        OnPropertyChanged(nameof(CircularDependencyCountText));
        OnPropertyChanged(nameof(ViolationCountText));
        OnPropertyChanged(nameof(LineCountText));
        OnPropertyChanged(nameof(DiagnosticsTitleText));
        OnPropertyChanged(nameof(OverlayModeText));
        OnPropertyChanged(nameof(MetricsFilterText));
        OnPropertyChanged(nameof(MetricsTabText));
        OnPropertyChanged(nameof(TopCoupledNamespacesText));
        OnPropertyChanged(nameof(HealthWarningsText));
        OnPropertyChanged(nameof(TopFilesByLineCountText));
        OnPropertyChanged(nameof(LinesUnitText));
        OnPropertyChanged(nameof(SettingsTitleText));
        OnPropertyChanged(nameof(SettingsDescriptionText));
        OnPropertyChanged(nameof(GraphSectionText));
        OnPropertyChanged(nameof(ShowLineCountText));
        OnPropertyChanged(nameof(LanguageText));
        OnPropertyChanged(nameof(TotalLocText));
        OnPropertyChanged(nameof(TotalFilesText));
        OnPropertyChanged(nameof(LargestFileText));
        OnPropertyChanged(nameof(LargestNamespaceText));
        OnPropertyChanged(nameof(CircularDependenciesText));
        OnPropertyChanged(nameof(LayerViolationsText));
        OnPropertyChanged(nameof(SymbolExplorerTabText));
        OnPropertyChanged(nameof(SymbolExplorerSearchPlaceholderText));
        OnPropertyChanged(nameof(SymbolExplorerSearchButtonText));
        OnPropertyChanged(nameof(SymbolExplorerDetailsTabText));
        OnPropertyChanged(nameof(SymbolExplorerFindRefsText));
        OnPropertyChanged(nameof(SymbolExplorerGoToDefText));
        OnPropertyChanged(nameof(SymbolExplorerTypeMembersTitleText));
        OnPropertyChanged(nameof(SymbolExplorerMethodMetaTitleText));
        OnPropertyChanged(nameof(BottomPanelDiagnosticsTabText));
        OnPropertyChanged(nameof(SymbolExplorerReferencesTabText));
        OnPropertyChanged(nameof(SymbolExplorerJumpOpenText));
        OnPropertyChanged(nameof(GroupByText));
        OnPropertyChanged(nameof(FitToScreenText));
        OnPropertyChanged(nameof(ZoomToSelectionText));
        OnPropertyChanged(nameof(CompactRelatedText));
        OnPropertyChanged(nameof(RestoreGraphPositionsText));
        OnPropertyChanged(nameof(ResetViewDefaultsText));
        OnPropertyChanged(nameof(FocusNeighborhoodOnlyText));
        OnPropertyChanged(nameof(ToolbarToggleText));
        OnPropertyChanged(nameof(DependencyPathTabText));
        OnPropertyChanged(nameof(DependencyPathSourceTextLabel));
        OnPropertyChanged(nameof(DependencyPathTargetTextLabel));
        OnPropertyChanged(nameof(DependencyPathShortestText));
        OnPropertyChanged(nameof(DependencyPathCycleText));
        OnPropertyChanged(nameof(DiagnosticsSeverityFilterText));
        OnPropertyChanged(nameof(ExportDiagnosticsText));
        OnPropertyChanged(nameof(RecentSearchesText));
        OnPropertyChanged(nameof(LogsTabText));
        OnPropertyChanged(nameof(PerformanceText));
        OnPropertyChanged(nameof(RestoreLastSessionText));
        OnPropertyChanged(nameof(AutoSaveSessionText));
        OnPropertyChanged(nameof(ThemeText));
        OnPropertyChanged(nameof(GraphLayoutText));
        OnPropertyChanged(nameof(CurrentVersionText));
        OnPropertyChanged(nameof(AvailableVersionsText));
        OnPropertyChanged(nameof(RefreshVersionsText));
        OnPropertyChanged(nameof(SwitchVersionText));
        OnPropertyChanged(nameof(UpdateHintText));
        OnPropertyChanged(nameof(MetricsTotalLoc));
        OnPropertyChanged(nameof(MetricsTotalFiles));
        OnPropertyChanged(nameof(MetricsLargestFile));
        OnPropertyChanged(nameof(MetricsLargestNamespace));
        OnPropertyChanged(nameof(MetricsCircularDependencies));
        OnPropertyChanged(nameof(MetricsLayerViolations));
        UpdateGraphStatus();
        UpdateTopStatus();
        if (_lastPerformanceSnapshot is not null)
        {
            PresentPerformanceSnapshot(_lastPerformanceSnapshot);
        }
    }
}
